title: メンチン至上主義 法務ドキュメント
description: 「メンチン至上主義」のプライバシーポリシー、利用規約、特定商取引法表記
theme: jekyll-theme-cayman
lang: ja

# Markdown プロセッサの設定
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 除外設定
exclude:
  - vendor
  - .bundle
  - Gemfile
  - Gemfile.lock
  - .gitignore
